# Site settings
title: Ether For Good
email: brenthompson2@gmail.com
description: Play games for a chance to win Ether while also donating to charities
# baseurl: "/jekyll-smart-material" # the subpath of your site, e.g. /blog/
# url: "http://ssokurenko.github.io" # the base hostname & protocol for your site
# copyright: '&copy; 2015-2016 Smart Material Theme'

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)
google-analytics-ua: UA-84475574-1
